---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  log_level: info

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2008R2-cvent

suites:
  - name: server
    run_list:
      - recipe[octopus-deploy-test::server]
    attributes:
      octopus-deploy-test:
        server:
          create-database: false
          start-service: false
  - name: tentacle
    run_list:
      - recipe[octopus-deploy-test::tentacle]
  - name: worker
    run_list:
      - recipe[octopus-deploy-test::worker]
  - name: tools
    run_list:
      - recipe[octopus-deploy-test::tools]
